### ISSUE TITLE
Testing on docker swarm

### ISSUE THREAD

**Issue by earthquakesan** [big-data-europe/docker-silk-workbench#1]
Please provide docker-compose v2 definition compatible with docker swarm and instructions on how to run silk inside swarm

**Comment by earthquakesan** [comment]
@gpapadis I just remembered that we had discussion on removing the Silk from the BDE platform as it is not used by any of SCs

**Comment by gpapadis** [comment]
Hi Ivan, 
yes, that's right, nobody is or will be using this dockerized component. Are you fine with deleting it?

**Comment by earthquakesan** [comment]
Hi George,

Please mark it with "[DISCONTINUED]" in the repository description. As you created Dockerfile, it might still be useful for someone, but we need to clearly indicate that we do not maintain this repo. Thanks!

**Comment by gpapadis** [comment]
Done!
